filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/mylogs/*.log

output.logstash:
  hosts: ["logstash:5044"]

processors:
  - add_docker_metadata:
      host: "unix:///host_docker/docker.sock"
